### PR TITLE
Addes input files relevant for the unit example

### PR DESCRIPTION
**Pull request by Manish-Khanra**
@nick-harder I have just committed the inpul files for the unit example. Could you please merge the pull request?

### CODE REVIEW

**Comment by nick-harder** [comment]
@Manish-Khanra please run tests before submitting PR. This one has failed due to the REUSE. Please add required headers and files

**Comment by nick-harder** [comment]
@Manish-Khanra also I am not sure why this needs to be a seperate commit. You could just add the files in the initial commit of the unit example. Or is this something specific?

**Comment by Manish-Khanra** [comment]
> @nick-harder What do you mean by 'This one has failed due to the REUSE'?
I needed a separate commit since I have to first include the input files in the main branch in order to successfully run the unit example script. It needs the required input from the main.

**Comment by nick-harder** [comment]
I mean, once it is commited, it would run.

I mean reuse is the specification, you can check out other input files for that. You can also install their package, it would do things automatically. I believe, Florian provided an instruction in the main github page for thay

**Review by nick-harder — APPROVED** [review]

**Pull request merged**
