### PR TITLE
Performance tuning

### PR DESCRIPTION
**Pull request by maurerle**
This improves performance of all simulations by a factor of 2 up to 4, by replacing pandas actions with numpy where possible.

For this, we are using a wrapper object FastDatetimeSeries which wraps a numpy array so that we can access it using typical datetime accessors

### CODE REVIEW

**Comment by nick-harder** [comment]
@maurerle hey, looks really promising! can I contribute in any way?

**Comment by maurerle** [comment]
There is still a lot to do:
* fix the tests
* eventually rename things, if they look unintuitive or create wrappers for easier usage
* fix all the type hints which are now outdated (should happen after renaming things of course)
* make sure learning works as well

Some timings from me:

`assume -s example_01a -db "postgresql+psycopg2://assume:assume@localhost:5432/assume"`

* main: `example_01a_base 2019-01-31 00:00:00: : 2592001.0it [00:28, 92397.33it/s]`
* tuning: `example_01a_base 2019-01-31 00:00:00: : 2592001.0it [00:14, 182495.12it/s]`

`assume -s example_01a ` (without writing to database at all)

* main: `example_01a_base 2019-01-31 00:00:00: : 2592001it [00:19, 132068.89it/s]`
* tuning: `example_01a_base 2019-01-31 00:00:00: : 2592001it [00:04, 620880.83it/s]`

`python examples/world_script.py`

* main: `world_script_simulation 2019-03-01 00:00:00: : 5097601.0it [00:06, 820487.43it/s]`
* tuning: `world_script_simulation 2019-03-01 00:00:00: : 5097601.0it [00:03, 1671636.28it/s]`

**Comment by nick-harder** [comment]
@maurerle I will work on this also tomorrow in the afternoon, please fill free to write me down tasks here that I should adress tomorrow

**Comment by nick-harder** [comment]
Succeeded by #483

**Pull request closed without merging**
