### PR TITLE
Add collab tonotebooks

### PR DESCRIPTION
**Pull request by nick-harder**
-added rl as notebook to the repository
-adjusted config to show collab at the top

### CODE REVIEW

**Comment by kim-mskw** [comment]
Love how easy and simple it look :) pretty cool! 

I was wondering if we should give an outlook and link the more complex implementations there as well? 
For example: Here we defined the market, in the advanced example this is done with YAML files. 

Or do you think that would be too confusing?

**Comment by nick-harder** [comment]
@kim-mskw yeah, these more compelx notebook will follow later. I wanted to construct dictsa and save them as csv files to demonstrate how to create a scenario and run it. For now I would like to find a good format for us to follow

**Comment by kim-mskw** [comment]
Yeah I know that it will follow later :) I was just wondering if we should mention or link the more complex option already somehow so that it is easier to draw the conclusion. Could be part of the structure then I guess.

**Comment by nick-harder** [comment]
@kim-mskw do you mean to add it directly in the notebook or what exactly? I don't understand. COuld you please make a suggestion directly? :-)

**Comment by kim-mskw** [comment]
Discussed in person

**Review by kim-mskw — APPROVED** [review]

**Pull request merged**
