### PR TITLE
Revisit and fix examples

### PR DESCRIPTION
**Pull request by nick-harder**
# Pull Request

## Related Issue
Closes #[issue number] (if applicable)

## Description
I have noticed, that several examples are not functional and decided to revisit them all and test them both locally and in Colab.

## Changes Proposed
- [List the main changes or features implemented]
-
-

## Testing
[Describe the testing you've done, including any specific test cases or scenarios]

## Checklist
Please check all applicable items:

- [x] Code changes are sufficiently documented (docstrings, inline comments, `doc` folder updates)
- [ ] New unit tests added for new features or bug fixes
- [ ] Existing tests pass with the changes
- [ ] Reinforcement learning examples are operational (for DRL-related changes)
- [x] Code tested with both local and Docker databases
- [x] Code follows project style guidelines and best practices
- [x] Changes are backwards compatible, or deprecation notices added
- [ ] New dependencies added to `pyproject.toml`
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included
- [x] Consent to release this PR's code under the GNU Affero General Public License v3.0

## Additional Notes (if applicable)
[Any additional information, concerns, or areas you want reviewers to focus on]

## Screenshots (if applicable)
[Add screenshots to demonstrate visual changes]

### CODE REVIEW

**Comment by nick-harder** [comment]
@maurerle I have noticed, that tutorial 5 the second OTC market example is not functional. Could you please take a look what is broken there? The problem seems to be with missing bidding strategies for the OTC market, but I am not sure how they should be defined.

**Comment by kim-mskw** [comment]
So the others are wokring? @nick-harder

**Comment by nick-harder** [comment]
@kim-mskw I have fixed the others, there were errors in the 3, 4, 6

**Review by maurerle — APPROVED** [review]

**Comment by maurerle** [comment]
This should be ready to merge to, isn't it?

**Comment by nick-harder** [comment]
@maurerle there are still some mistakes, my HiWi is working on it right now with a fresh eye. I will merge when ready

**Comment by nick-harder** [comment]
@kim-mskw @mthede the latest commit with the LSTM strategy has broken the Notebook 4 DRL as we noticed now. Could you please bring it to the latest stand and to working condition and commit it to this branch?

**Comment by Sarilein** [comment]
@maurerle The issue begins with world.loop.run_until_complete under the point "3. Load AMIRIS scenario":
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-3-b5a7be73bad0>](https://localhost:8080/#) in <cell line: 10>()
      8 db_uri = "sqlite:///test.db"
      9 world = World(database_uri=db_uri)
---> 10 world.loop.run_until_complete(
     11     load_amiris_async(
     12         world,

4 frames

[/usr/local/lib/python3.10/dist-packages/assume/scenario/loader_amiris.py](https://localhost:8080/#) in read_amiris_yaml(base_path)
    443 
    444 def read_amiris_yaml(base_path):
--> 445     Constructor.add_to_loader_class(loader_class=yaml.FullLoader, base_dir=base_path)
    446 
    447     with open(base_path + "/scenario.yaml", "rb") as f:

AttributeError: type object 'Constructor' has no attribute 'add_to_loader_class

**Comment by maurerle** [comment]
thanks @Sarilein - see #413 which includes a fix of downgrading pyyaml-include for now and reverting the switch to 2.x

**Comment by nick-harder** [comment]
> @kim-mskw @mthede the latest commit with the LSTM strategy has broken the Notebook 4 DRL as we noticed now. Could you please bring it to the latest stand and to working condition and commit it to this branch?

Hi @kim-mskw @mthede could you please update me on the status of this fix? There are a few people who would like to start with ASSUME, but I cannot recommend them the tutorial as now they are not functional. It would be really nice if we could release the version with fixed tutorials today or tomorrow. Thank you both in advance :-)

**Comment by maurerle** [comment]
Currently `example_02a` and `example_01c - dam_with_complex_opt_clearing` does not work.
If this is fixed, we should merge this :)

**Comment by nick-harder** [comment]
@maurerle example 6 has been fixed, and the rest of them have been retested. Tutorial 4 is not functional, but we will fix it in a different commit. Could you please take a look at tutorial 7, one of the CLI commands at the beginning doesn't work locally

**Pull request merged**
